### ISSUE TITLE
Any suggestion for adding click handler to each Kanji?

### ISSUE THREAD

**Issue by xuanchien** [lofe90/FuriganaTextView#1]
Hi @lofe90 
Thank you for providing this widget. I am working on a simple project which I need to allow users to click on the Kanji to view the meaning. Do you have any suggestion to do that? I am new to Android and I don't know exactly how to accomplish this. 

Thank you in advance.

**Comment by lofe90** [comment]
Hello,
What you could do is to write a method that goes through your String and identifies each block of kanji. For example {彼女;かのじょ} is a kanji block. You could put each block that you identify in a new FuriganaTextView instance then simply call setOnClickListener on each FuriganaTextView and add it to a horizontally aligned LinearLayout.

Might not be the best soluton but, hope this helps :)
